import os


folders = [
  "no_lens_distortion",
  "with_lens_distortion",
  "fisheye_distortion",
  "barrel_distortion",
  "broadcast_pov",
  "dashcam_pov",
  "drone_pov",
  "first_person_pov",
  "locked_on_pov",
  "overhead_pov",
  "screen_recording_pov",
  "selfie_pov",
  "third_person_full_body_game_pov",
  "third_person_isometric_game_pov",
  "third_person_over_hip_pov",
  "third_person_over_shoulder_pov",
  "third_person_side_view_game_pov",
  "third_person_top_down_game_pov",
  "objective_pov",
  "true_pov_attribute",
  "is_framing_subject",
  "has_subject_change",
  "has_single_dominant_subject",
  "has_many_subjects",
  "is_human_shot",
  "is_non_human_shot",
  "is_just_human_shot",
  "is_just_non_human_shot",
  "is_just_change_of_subject_shot",
  "is_just_scenery_shot",
  "is_just_clear_subject_dynamic_size_shot",
  "is_just_different_subject_in_focus_shot",
  "is_just_clear_subject_atypical_shot",
  "is_just_many_subject_one_focus_shot",
  "is_just_many_subject_no_focus_shot",
  "is_just_subject_scene_mismatch_shot",
  "is_just_back_and_forth_change_shot",
  "is_shot_size_applicable",
  "subject_revealing",
  "subject_disappearing",
  "subject_switching",
  "shot_size_change",
  "shot_size_change_from_large_to_small",
  "shot_size_change_from_small_to_large",
  "is_subject_height_applicable",
  "height_wrt_subject_change_from_high_to_low",
  "height_wrt_subject_change_from_low_to_high",
  "height_wrt_subject_change",
  "is_height_wrt_ground_applicable",
  "height_wrt_ground_change_from_high_to_low",
  "height_wrt_ground_change_from_low_to_high",
  "above_water_to_underwater",
  "underwater_to_above_water",
  "height_wrt_ground_change",
  "is_camera_angle_applicable",
  "is_dutch_angle",
  "is_dutch_angle_varying",
  "is_dutch_angle_fixed",
  "camera_angle_change_from_high_to_low",
  "camera_angle_change_from_low_to_high",
  "camera_angle_change",
  "is_focus_applicable",
  "is_deep_focus",
  "is_shallow_focus",
  "is_ultra_shallow_focus",
  "focus_change_from_near_to_far",
  "focus_change_from_far_to_near",
  "is_rack_pull_focus",
  "is_focus_tracking",
  "focus_change",
  "is_rack_focus",
  "is_pull_focus",
  "focus_change_from_in_to_out_of_focus",
  "focus_change_from_out_to_in_focus"
]

for folder in folders:
    path = f'./dataset/camerapizza/{folder}'
    os.makedirs(path, exist_ok=True)